# Generated by Django 5.1.6 on 2025-04-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('rub', 'RUB'), ('kzt', 'KZT')], max_length=3)),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'constraints': [models.UniqueConstraint(fields=('source_name', 'currency_code'), name='unique_exchange_rate')],
            },
        ),
    ]
