# Generated by Django 5.1.6 on 2025-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangerate',
            name='unique_exchange_rate',
        ),
        migrations.RenameField(
            model_name='exchangerate',
            old_name='buy_rate',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='sell_rate',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='source_name',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_code',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('rub', 'RUB'), ('kzt', 'KZT')], max_length=3, unique=True),
        ),
    ]
