# Generated by Django 5.1.6 on 2025-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Initial balance'),
        ),
    ]
